name: Release

on:
  push:

# necessary to create releases
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: grafana/plugin-actions/bundle-types@jackw/types-bundler-action
