name: Types

on:
  push:

jobs:
  bundle-types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: grafana/plugin-actions/bundle-types@jackw/types-bundler-action
        with:
          entryPoint: ${{ github.workspace }}/src/types/index.ts
          tsConfig: ${{ github.workspace }}/tsconfig.json
